const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes={},ctx=new Proxy({measureText:t=>({width:String(t).length*7}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:()=>{}});function el(){return{children:[],style:{},classList:{add(){},remove(){}},dataset:{},open:false,getContext:()=>ctx,append(...c){this.children.push(...c);},replaceChildren(){this.children=[];},showModal(){this.open=true;},close(){this.open=false;},addEventListener(){},click(){this.onclick?.();}};}let saved={};const sandbox={document:{querySelector:s=>nodes[s]??=el(),querySelectorAll:()=>[],createElement:el,addEventListener(){},hidden:false},window:{addEventListener(){}},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v},requestAnimationFrame(){},performance:{now:()=>0},setTimeout(){},clearTimeout(){},console};vm.createContext(sandbox);for(const file of ['data','world','renderer','art','jobs','navigation','progression','game'])vm.runInContext(fs.readFileSync(`dist/${file}.js`,'utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox),check=s=>assert.equal(run(s),true,s);check('MW.regions.length===12&&MW.steps.length===9');
// Reachability of every usable object on all 12 maps, without moving through walls.
for(let region=0;region<12;region++){run(`game.p.unlocked=11;game.enter(${region});`);const unreachable=run(`(()=>{const w=game.world,seen=new Set(),queue=[[11,28]];while(queue.length){const [x,y]=queue.shift(),k=x+','+y;if(seen.has(k)||w.solid(x*48,y*48))continue;seen.add(k);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(x+dx>1&&x+dx<78&&y+dy>1&&y+dy<52)queue.push([x+dx,y+dy]);}return [...w.objects,...w.npcs].filter(o=>![...seen].some(k=>{const [x,y]=k.split(',').map(Number);return Math.hypot(x*48-o.x,y*48-o.y)<100})).map(o=>o.name+' '+o.id);})()`);assert.equal(unreachable.length,0,`Map ${region}: ${unreachable}`);run('game.renderer.draw(game,.02)');}
// Execute each objective kind and claim the reward on every story chapter.
for(let region=0;region<12;region++){run(`game.enter(${region});game.p.x=game.world.npcs[0].x;game.p.y=game.world.npcs[0].y;game.interact();`);nodes['#choices'].children[0].click();check('game.q().step===1');for(const index of [0,1,3])run(`game.landmark(game.world.objects.find(o=>o.id==='land${index}'));dialog.close();`);check('game.q().step===2');run('game.count("kill",game.required())');check('game.q().step===3');for(let i=0;i<10;i++)run(`game.p.x=game.world.objects.find(o=>o.id==='memory${i}').x;game.p.y=game.world.objects.find(o=>o.id==='memory${i}').y;game.interact();`);check('game.q().step===4');run('game.puzzle=[];game.puzzleMenu()');const order=run('MW.regions[game.p.region].puzzle');for(const n of order)nodes['#choices'].children[n-1].click();check('game.q().step===5');run('game.escort={x:11*48,y:28*48,hp:300};game.update(.01)');check('game.q().step===6');run('game.landmark(game.world.objects.find(o=>o.id==="land1"))');for(let wave=0;wave<5;wave++)run('game.enemies.filter(e=>e.event&&!e.dead).forEach(e=>game.kill(e));game.update(.01)');check('game.q().step===7');run('game.kill(game.enemies.find(e=>e.boss));game.p.x=game.world.npcs[0].x;game.p.y=game.world.npcs[0].y;game.interact()');nodes['#choices'].children[0].click();check('game.q().step===9');}
run("game.enter(0);game.p.gold=1000;game.shop(game.world.npcs.find(n=>n.role==='weapons'))");const item=nodes['#dialogtext'].children[0].children.find(c=>c.children[0].textContent==='월영검');assert.ok(item);item.children[2].click();check('game.p.equip.weapon==="weapon1"');const gold=run('game.p.gold');item.children[2].click();assert.equal(run('game.p.gold'),gold,'Duplicate equipment purchase');run('dialog.close();game.p.hp=20;game.use("potion")');check('game.p.hp===140');run('game.p.mp=0;game.use("ether")');check('game.p.mp===80');
run('game.startTower(5)');for(let i=0;i<4;i++)run('game.enemies.filter(e=>e.tower&&!e.dead).forEach(e=>game.kill(e));game.update(.01)');check('game.p.towerBest===5&&game.p.towerRewards.includes(5)');run('dialog.close();game.enter(0);game.save()');check('game.valid(JSON.parse(localStorage.getItem("moonwind-v2")))');check('!game.valid({version:2,region:99})');
// All 72 expedition floors: connected rooms, seal combat gate, boss and checkpoint.
for(let region=0;region<12;region++)for(let floor=1;floor<=6;floor++){
 run(`dialog.close();game.enter(${region});game.startDungeon(${floor})`);
 const reachable=run(`(()=>{const w=game.world,queue=[[13,16]],seen=new Set();while(queue.length){const [x,y]=queue.shift(),k=x+','+y;if(seen.has(k)||w.solid(x*48,y*48))continue;seen.add(k);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(x+dx>1&&x+dx<78&&y+dy>1&&y+dy<52)queue.push([x+dx,y+dy]);}return w.objects.every(o=>[...seen].some(k=>{const [x,y]=k.split(',').map(Number);return Math.hypot(x*48-o.x,y*48-o.y)<100}));})()`);assert.equal(reachable,true,`Dungeon ${region} floor ${floor}`);
 run('game.enemies.forEach(e=>game.kill(e))');
 for(let i=0;i<3;i++)run(`game.p.x=game.world.objects[${i}].x;game.p.y=game.world.objects[${i}].y;game.dungeonInteract()`);
 check('game.dungeon.seals.length===3&&game.enemies.some(e=>e.expedition&&e.boss)');
 run('game.kill(game.enemies.find(e=>e.boss));game.updateDungeon()');check(`game.p.expeditions[${region}]===${floor}`);run('game.renderer.draw(game,.02)');
}
run('dialog.close();game.enter(0);game.save()');check('game.valid(JSON.parse(localStorage.getItem("moonwind-v2")))');
for(let region=0;region<12;region++)for(let side=0;side<3;side++){
 run(`game.enter(${region});game.p.side[${region}][${side}].accepted=true;game.p.side[${region}][${side}].count=game.sideNeed(${side});game.sideMenu(game.world.npcs[3])`);
 const card=nodes['#dialogtext'].children[0].children[side];const rewardButton=card.children.find(c=>c.textContent==='보상 받기');assert.ok(rewardButton);rewardButton.click();check(`game.p.side[${region}][${side}].done===true`);run('dialog.close()');
}
console.log('PASS: 24 map types/72 dungeon floors reachable; 108 story and 36 side quest rewards; defense, escort, puzzle, shop/equipment/consumables, tower, save validation and rendering.');
// The unified action must fight nearby enemies before opening an NPC dialog.
run('dialog.close();game.enter(0);game.enemies=[];game.p.x=game.world.npcs[0].x;game.p.y=game.world.npcs[0].y;');
check("game.primaryMode()==='talk'");run('game.primaryAction()');check('dialog.open');run('dialog.close();game.cool.attack=0;game.enemies=[{x:game.p.x+40,y:game.p.y,hp:100,max:100,dead:false,seed:1}];game.primaryAction()');check('!dialog.open&&game.enemies[0].hp<100');
// Collecting an item stops held input and removes the used item from action targeting.
run("game.enemies=[];game.world.npcs=[];game.world.objects=[game.world.objects.find(o=>o.type==='memory')];game.p.x=game.world.objects[0].x;game.p.y=game.world.objects[0].y;game.collected.clear();game.keys.add(' ');");check("game.primaryMode()==='inspect'");run('game.primaryAction()');check("game.collected.has(game.world.objects[0].id)&&!game.keys.has(' ')&&game.primaryMode()==='attack'");
console.log('PASS: unified action NPC dialog, enemy priority, collection and held-input release.');

// Device saves, backup recovery, shop separation, and all attack modes.
run('dialog.close();game.enter(0);game.shop(game.world.npcs[1])');
assert.ok(nodes['#dialogtext'].children[0].children.every(c=>run('MW.items.filter(i=>i.type==="use").map(i=>i.name)').includes(c.children[0].textContent)));
run("game.shop(game.world.npcs.find(n=>n.role==='weapons'))");
assert.ok(nodes['#dialogtext'].children[0].children.every(c=>run('MW.items.filter(i=>i.type!=="use").map(i=>i.name)').includes(c.children[0].textContent)));
run('dialog.close();game.p.gold=4321;game.save();game.p=game.fresh();game.load()');check('game.p.gold===4321&&game.p.savedAt>0');
saved['moonwind-v2-backup']=saved['moonwind-v2'];saved['moonwind-v2']='{broken';run('game.p=game.fresh();game.load()');check('game.p.gold===4321&&game.p.log.some(t=>t.includes("복구"))');
const write=sandbox.localStorage.setItem;sandbox.localStorage.setItem=()=>{throw Error('storage unavailable')};run('game.save()');check('!game.saveOK');sandbox.localStorage.setItem=write;run('game.save()');check('game.saveOK');
for(const [kind,weapon,skill] of [['unarmed',null,false],['weapon','weapon1',false],['skill','weapon1',true]]){run('dialog.close();game.enemies=[];game.cool.attack=0;game.cool.skill=0;game.p.mp=100;game.p.equip.weapon='+JSON.stringify(weapon)+';game.attack('+skill+')');check('game.strike.kind==='+JSON.stringify(kind));run('game.renderer.draw(game,.02)');}
check('game.p.mp===75');console.log('PASS: separate potion/equipment shops; device save and backup recovery; write failures; unarmed, weapon, and skill effects.');

// Advancement gates, starter equipment, reclassing without losing items, and save compatibility.
run('dialog.close();game.p=game.fresh();game.enter(0);game.changeJob("warrior")');check('game.p.job==="traveler"');
run('game.p.level=3;game.p.x=1200;game.changeJob("mage")');check('game.p.job==="traveler"');run('game.p.x=528');
for(const job of ['warrior','archer','mage']){run('game.changeJob('+JSON.stringify(job)+')');check('game.p.job==='+JSON.stringify(job));check('game.p.owned.includes(game.p.equip.weapon)&&game.p.owned.includes(game.p.equip.armor)');check('game.valid(game.p)');check('game.p.hp===game.stats().hp');for(let face=0;face<4;face++)for(let tier=1;tier<=4;tier++){run('game.renderer.player({job:'+JSON.stringify(job)+',equip:{weapon:'+(job==='warrior'?'"weapon'+tier+'"':JSON.stringify(job+'weapon'+tier))+',armor:'+JSON.stringify(job+'armor'+tier)+'}},'+face+',1)');}run('dialog.close();game.cool.attack=0;game.cool.skill=0;game.attack(true);game.renderer.draw(game,.02)');}
const owned=run('game.p.owned.length');run('game.changeJob("warrior");game.changeJob("mage")');assert.equal(run('game.p.owned.length'),owned);
run('game.save();game.p=game.fresh();game.load()');check('game.p.job==="mage"&&game.p.equip.armor==="magearmor1"');
check('!game.valid({...game.p,job:"rogue"})');check('!game.valid({...game.p,job:"archer"})');check('game.valid({...game.fresh(),job:undefined})');
// Ranged basic attacks hit in the facing direction and respect their range.
for(const [job,range]of [['warrior',80],['archer',230],['mage',200]]){run('dialog.close();game.changeJob('+JSON.stringify(job)+');dialog.close();game.face=1;game.cool.attack=0;game.enemies=[{x:game.p.x+'+(range-5)+',y:game.p.y,hp:10000,max:10000,seed:1},{x:game.p.x+300,y:game.p.y,hp:10000,max:10000,seed:2},{x:game.p.x-180,y:game.p.y,hp:10000,max:10000,seed:3}];game.attack()');check('game.enemies[0].hp<10000&&game.enemies[1].hp===10000&&game.enemies[2].hp===10000');}
run('game.inventory()');const armorCard=nodes['#dialogtext'].children[0].children.find(c=>c.children[0]?.textContent==='방어구');armorCard.children[2].click();check('game.p.equip.armor===null');run('game.save();game.p=game.fresh();game.load()');check('game.p.equip.armor===null');
console.log('PASS: advancement gates, all 3 jobs/4 directions/4 gear tiers, ownership retention, class save migration, ranged combat and visible gear removal.');

// Route-following integrates with real collision, discovery, collection and combat.
run('dialog.close();game.p=game.fresh();game.enter(0);game.enemies=[];game.toggleAuto();for(let i=0;i<1000&&game.auto;i++)game.update(.05)');check('dialog.open&&!game.auto&&Math.hypot(game.p.x-game.world.npcs[0].x,game.p.y-game.world.npcs[0].y)<105');
run('dialog.close();game.q().step=1;game.toggleAuto();for(let i=0;i<12000&&game.auto;i++){dialog.close();game.update(.05)}');check('game.q().step===2&&!game.auto&&Number.isFinite(game.p.x)&&Number.isFinite(game.p.y)');
run('game.q().step=3;game.q().count=0;game.enter(0);game.enemies=[];game.toggleAuto();for(let i=0;i<18000&&game.auto;i++){dialog.close();game.update(.05)}');check('game.q().step===4&&game.q().memories.length>=10&&!game.auto');
run('dialog.close();game.p=game.fresh();game.p.level=10;game.enter(0);game.q().step=2;game.q().count=35;game.enemies=game.enemies.slice(0,1);game.enemies[0].hp=1;game.toggleAuto();for(let i=0;i<5000&&game.auto;i++)game.update(.05)');check('game.q().step===3&&!game.auto&&Number.isFinite(game.p.x)');
run('game.toggleAuto();game.stopAuto();');check('!game.auto&&!game.moving&&game.keys.size===0');
run('game.regionMap()');check('game.paused&&document.querySelector("#regionmap").open');run('game.drawRegionMap()');
console.log('PASS: collision-aware automatic travel, 3 landmarks, 10 collectibles, automatic hunt completion, cancellation, and full region map rendering.');

// Transaction guards and one-time starter grants prevent resale farming.
run('dialog.close();game.paused=false;game.p=game.fresh();game.p.level=10;game.enter(0);game.changeJob("warrior");dialog.close()');check('!game.disposeItem("weapon1","sell",1)');run('game.p.equip.weapon=null');const oldGold=run('game.p.gold');check('game.disposeItem("weapon1","sell",1)');assert.equal(run('game.p.gold'),oldGold+64);check('!game.p.owned.includes("weapon1")&&!game.disposeItem("weapon1","sell",1)');run('game.changeJob("mage");game.changeJob("warrior");dialog.close()');check('!game.p.owned.includes("weapon1")&&game.p.starterClaims.includes("warrior")');
run('game.p.equip.armor=null');const ore=run('game.p.bag.ore');check('game.disposeItem("warriorarmor1","salvage",1)');assert.equal(run('game.p.bag.ore'),ore+2);check('!game.disposeItem("potion","salvage",1)&&!game.disposeItem("potion","sell",-1)&&!game.disposeItem("potion","sell",999)');const potions=run('game.p.bag.potion');check('game.disposeItem("potion","sell",3)');assert.equal(run('game.p.bag.potion'),potions-3);
// All advanced jobs require level 10 and retain their record after switching or reloading.
for(const id of ['warrior','archer','mage']){run('game.p.level=9;game.changeJob('+JSON.stringify(id)+');dialog.close()');check('!game.promote('+JSON.stringify(id)+')');const before=run('game.stats().atk');run('game.p.level=10');check('game.promote('+JSON.stringify(id)+')');check('game.p.promotions.includes('+JSON.stringify(id)+')&&game.stats().atk>'+before);check('!game.promote('+JSON.stringify(id)+')');run('dialog.close();game.cool.attack=0;game.cool.skill=0;game.p.mp=100;game.attack(true)');check('game.strike.promoted&&game.cool.skill===3.5');run('game.renderer.draw(game,.02)');}
run('game.save();game.p=game.fresh();game.load()');check('game.p.promotions.length===3&&game.p.starterClaims.length===3&&game.valid(game.p)');check('!game.valid({...game.p,promotions:["rogue"]})&&!game.valid({...game.p,level:9})');
run('game.p=game.fresh();game.ensureProgression();game.openGuide()');check('!document.querySelector("#guide-tooltip").hidden&&game.currentGuide.key==="quest:talk"');run('game.closeGuide();game.guideUI()');check('document.querySelector("#guide-tooltip").hidden');run('game.openGuide()');check('!document.querySelector("#guide-tooltip").hidden');run('game.p.level=3');check('game.guideContext().key==="firstjob"');run('game.p.level=10;game.p.job="mage"');check('game.guideContext().key==="promotion:mage"');
console.log('PASS: protected equipment, stack sales, salvage rewards, duplicate transaction rejection, starter grant farming prevention, all 3 level-10 advancements, save persistence and contextual guides.');
