const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes={},ctx=new Proxy({measureText:t=>({width:String(t).length*7}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>k in o?o[k]:()=>{}});function el(){return{children:[],style:{},classList:{add(){},remove(){}},dataset:{},open:false,getContext:()=>ctx,append(...c){this.children.push(...c);},replaceChildren(){this.children=[];},showModal(){this.open=true;},close(){this.open=false;},addEventListener(){},click(){this.onclick?.();}};}let saved={};const sandbox={document:{querySelector:s=>nodes[s]??=el(),querySelectorAll:()=>[],createElement:el,addEventListener(){},hidden:false},window:{addEventListener(){}},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v},requestAnimationFrame(){},performance:{now:()=>0},setTimeout(){},clearTimeout(){},console};vm.createContext(sandbox);for(const file of ['data','world','renderer','art','game'])vm.runInContext(fs.readFileSync(`dist/${file}.js`,'utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox),check=s=>assert.equal(run(s),true,s);check('MW.regions.length===12&&MW.steps.length===9');
// Reachability of every usable object on all 12 maps, without moving through walls.
for(let region=0;region<12;region++){run(`game.p.unlocked=11;game.enter(${region});`);const unreachable=run(`(()=>{const w=game.world,seen=new Set(),queue=[[11,28]];while(queue.length){const [x,y]=queue.shift(),k=x+','+y;if(seen.has(k)||w.solid(x*48,y*48))continue;seen.add(k);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(x+dx>1&&x+dx<78&&y+dy>1&&y+dy<52)queue.push([x+dx,y+dy]);}return [...w.objects,...w.npcs].filter(o=>![...seen].some(k=>{const [x,y]=k.split(',').map(Number);return Math.hypot(x*48-o.x,y*48-o.y)<100})).map(o=>o.name+' '+o.id);})()`);assert.equal(unreachable.length,0,`Map ${region}: ${unreachable}`);run('game.renderer.draw(game,.02)');}
// Execute each objective kind and claim the reward on every story chapter.
for(let region=0;region<12;region++){run(`game.enter(${region});game.p.x=game.world.npcs[0].x;game.p.y=game.world.npcs[0].y;game.interact();`);nodes['#choices'].children[0].click();check('game.q().step===1');for(const index of [0,1,3])run(`game.landmark(game.world.objects.find(o=>o.id==='land${index}'));dialog.close();`);check('game.q().step===2');run('game.count("kill",game.required())');check('game.q().step===3');for(let i=0;i<10;i++)run(`game.p.x=game.world.objects.find(o=>o.id==='memory${i}').x;game.p.y=game.world.objects.find(o=>o.id==='memory${i}').y;game.interact();`);check('game.q().step===4');run('game.puzzle=[];game.puzzleMenu()');const order=run('MW.regions[game.p.region].puzzle');for(const n of order)nodes['#choices'].children[n-1].click();check('game.q().step===5');run('game.escort={x:11*48,y:28*48,hp:300};game.update(.01)');check('game.q().step===6');run('game.landmark(game.world.objects.find(o=>o.id==="land1"))');for(let wave=0;wave<5;wave++)run('game.enemies.filter(e=>e.event&&!e.dead).forEach(e=>game.kill(e));game.update(.01)');check('game.q().step===7');run('game.kill(game.enemies.find(e=>e.boss));game.p.x=game.world.npcs[0].x;game.p.y=game.world.npcs[0].y;game.interact()');nodes['#choices'].children[0].click();check('game.q().step===9');}
run("game.enter(0);game.p.gold=1000;game.shop(game.world.npcs.find(n=>n.role==='weapons'))");const item=nodes['#dialogtext'].children[0].children.find(c=>c.children[0].textContent==='월영검');assert.ok(item);item.children[2].click();check('game.p.equip.weapon==="weapon1"');const gold=run('game.p.gold');item.children[2].click();assert.equal(run('game.p.gold'),gold,'Duplicate equipment purchase');run('dialog.close();game.p.hp=20;game.use("potion")');check('game.p.hp===140');run('game.p.mp=0;game.use("ether")');check('game.p.mp===80');
run('game.startTower(5)');for(let i=0;i<4;i++)run('game.enemies.filter(e=>e.tower&&!e.dead).forEach(e=>game.kill(e));game.update(.01)');check('game.p.towerBest===5&&game.p.towerRewards.includes(5)');run('dialog.close();game.enter(0);game.save()');check('game.valid(JSON.parse(localStorage.getItem("moonwind-v2")))');check('!game.valid({version:2,region:99})');
// All 72 expedition floors: connected rooms, seal combat gate, boss and checkpoint.
for(let region=0;region<12;region++)for(let floor=1;floor<=6;floor++){
 run(`dialog.close();game.enter(${region});game.startDungeon(${floor})`);
 const reachable=run(`(()=>{const w=game.world,queue=[[13,16]],seen=new Set();while(queue.length){const [x,y]=queue.shift(),k=x+','+y;if(seen.has(k)||w.solid(x*48,y*48))continue;seen.add(k);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]])if(x+dx>1&&x+dx<78&&y+dy>1&&y+dy<52)queue.push([x+dx,y+dy]);}return w.objects.every(o=>[...seen].some(k=>{const [x,y]=k.split(',').map(Number);return Math.hypot(x*48-o.x,y*48-o.y)<100}));})()`);assert.equal(reachable,true,`Dungeon ${region} floor ${floor}`);
 run('game.enemies.forEach(e=>game.kill(e))');
 for(let i=0;i<3;i++)run(`game.p.x=game.world.objects[${i}].x;game.p.y=game.world.objects[${i}].y;game.dungeonInteract()`);
 check('game.dungeon.seals.length===3&&game.enemies.some(e=>e.expedition&&e.boss)');
 run('game.kill(game.enemies.find(e=>e.boss));game.updateDungeon()');check(`game.p.expeditions[${region}]===${floor}`);run('game.renderer.draw(game,.02)');
}
run('dialog.close();game.enter(0);game.save()');check('game.valid(JSON.parse(localStorage.getItem("moonwind-v2")))');
for(let region=0;region<12;region++)for(let side=0;side<3;side++){
 run(`game.enter(${region});game.p.side[${region}][${side}].accepted=true;game.p.side[${region}][${side}].count=game.sideNeed(${side});game.sideMenu(game.world.npcs[3])`);
 const card=nodes['#dialogtext'].children[0].children[side];const rewardButton=card.children.find(c=>c.textContent==='보상 받기');assert.ok(rewardButton);rewardButton.click();check(`game.p.side[${region}][${side}].done===true`);run('dialog.close()');
}
console.log('PASS: 24 map types/72 dungeon floors reachable; 108 story and 36 side quest rewards; defense, escort, puzzle, shop/equipment/consumables, tower, save validation and rendering.');
// The unified action must fight nearby enemies before opening an NPC dialog.
run('dialog.close();game.enter(0);game.enemies=[];game.p.x=game.world.npcs[0].x;game.p.y=game.world.npcs[0].y;');
check("game.primaryMode()==='talk'");run('game.primaryAction()');check('dialog.open');run('dialog.close();game.cool.attack=0;game.enemies=[{x:game.p.x+40,y:game.p.y,hp:100,max:100,dead:false,seed:1}];game.primaryAction()');check('!dialog.open&&game.enemies[0].hp<100');
// Collecting an item stops held input and removes the used item from action targeting.
run("game.enemies=[];game.world.npcs=[];game.world.objects=[game.world.objects.find(o=>o.type==='memory')];game.p.x=game.world.objects[0].x;game.p.y=game.world.objects[0].y;game.collected.clear();game.keys.add(' ');");check("game.primaryMode()==='inspect'");run('game.primaryAction()');check("game.collected.has(game.world.objects[0].id)&&!game.keys.has(' ')&&game.primaryMode()==='attack'");
console.log('PASS: unified action NPC dialog, enemy priority, collection and held-input release.');

// Device saves, backup recovery, shop separation, and all attack modes.
run('dialog.close();game.enter(0);game.shop(game.world.npcs[1])');
assert.ok(nodes['#dialogtext'].children[0].children.every(c=>run('MW.items.filter(i=>i.type==="use").map(i=>i.name)').includes(c.children[0].textContent)));
run("game.shop(game.world.npcs.find(n=>n.role==='weapons'))");
assert.ok(nodes['#dialogtext'].children[0].children.every(c=>run('MW.items.filter(i=>i.type!=="use").map(i=>i.name)').includes(c.children[0].textContent)));
run('dialog.close();game.p.gold=4321;game.save();game.p=game.fresh();game.load()');check('game.p.gold===4321&&game.p.savedAt>0');
saved['moonwind-v2-backup']=saved['moonwind-v2'];saved['moonwind-v2']='{broken';run('game.p=game.fresh();game.load()');check('game.p.gold===4321&&game.p.log.some(t=>t.includes("복구"))');
const write=sandbox.localStorage.setItem;sandbox.localStorage.setItem=()=>{throw Error('storage unavailable')};run('game.save()');check('!game.saveOK');sandbox.localStorage.setItem=write;run('game.save()');check('game.saveOK');
for(const [kind,weapon,skill] of [['unarmed',null,false],['weapon','weapon1',false],['skill','weapon1',true]]){run('dialog.close();game.enemies=[];game.cool.attack=0;game.cool.skill=0;game.p.mp=100;game.p.equip.weapon='+JSON.stringify(weapon)+';game.attack('+skill+')');check('game.strike.kind==='+JSON.stringify(kind));run('game.renderer.draw(game,.02)');}
check('game.p.mp===75');console.log('PASS: separate potion/equipment shops; device save and backup recovery; write failures; unarmed, weapon, and skill effects.');
